- hosts: all
  become: true
  ignore_errors: yes
  
  tasks:
  - name: stop container
    command: docker stop car-app
    ignore_errors: yes
    
  - name: remove stopped container
    command: docker rm car-app
    ignore_errors: yes
    
  - name: run container
    command: docker run -d --name car-app -p 8080:8080 nolancon/car-app:latest
